# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1
package:
  name: ros-humble-test-wasm
  version: 1.0.0

source:
  git: https://github.com/ihuicatl/rmw_wasm.git
  rev: main
  target_directory: ros-humble-test-wasm/src/work
  patches:
    - fix-build.patch

build:
  script:
    build.sh
  number: 1
  skip:
    - not emscripten-wasm32

about:
  homepage: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

requirements:
  build:
    - if: target_platform == 'emscripten-wasm32'
      then:
        - emscripten_emscripten-wasm32
      else:
        - ${{compiler('c')}}
        - ${{compiler('cxx')}}
    - if: linux64
      then:
        - sysroot_linux-64 2.17
    - if: unix
      then:
        - make
        - coreutils
    - if: osx
      then: tapi
    - if: build_platform != target_platform
      then:
        - pkg-config
        - python
        - cross-python_${{target_platform}}
        - cython
        - numpy
    - ninja
    - setuptools
    - cmake
  host:
    - numpy
    - pip
    - if: build_platform == target_platform
      then:
        - pkg-config
    - python
    - ros-humble-ament-cmake
    - ros-humble-rclcpp
    - ros-humble-std-msgs
    - ros-humble-example-interfaces
    - ros-humble-yaml-cpp-vendor
    - yaml
    - yaml-cpp
    - ros2-distro-mutex 0.6.* humble_*
    - sqlite
    - bzip2
    - zlib
    - ros-humble-rmw-wasm-cpp
    - libffi
  run:
    - if: target_platform != 'emscripten-wasm32'
      then:
        - cmake
    - python
    - ros-humble-rclcpp
    - ros-humble-std-msgs
    - ros-humble-example-interfaces
    - ros-humble-yaml-cpp-vendor
    - ros2-distro-mutex 0.6.* humble_*
    - if: (osx and x86_64)
      then: __osx >=${{MACOSX_DEPLOYMENT_TARGET|default('10.14')}}
